package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/IIOP_CLEAR_TEXT.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON3/workspace/8-2-build-linux-amd64/jdk8u141/9370/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Wednesday, July 12, 2017 4:22:36 AM PDT
*/

public interface IIOP_CLEAR_TEXT
{

  // to avoid a compilation dependency.
  public static final String value = "IIOP_CLEAR_TEXT";
}
