package org.omg.PortableServer;


/**
* org/omg/PortableServer/SERVANT_RETENTION_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /HUDSON3/workspace/8-2-build-linux-amd64/jdk8u141/9370/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Wednesday, July 12, 2017 4:22:39 AM PDT
*/

public interface SERVANT_RETENTION_POLICY_ID
{

  /**
  	 * The value representing SERVANT_RETENTION_POLICY_ID.
  	 */
  public static final int value = (int)(21L);
}
